# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "quiet" "i915.force_probe=a7a0" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/84e99a7c-67f5-4a0b-8d61-7e47e8856238";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-15793ff1-6b02-41c8-8fdb-7bfac7647ae2".device = "/dev/disk/by-uuid/15793ff1-6b02-41c8-8fdb-7bfac7647ae2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ED14-B2D1";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/25c39e57-9ff4-410e-bc86-92bd8885c997";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-497a1bc2-a33b-49e0-8f7e-da66bbf7e9ed".device = "/dev/disk/by-uuid/497a1bc2-a33b-49e0-8f7e-da66bbf7e9ed";

  boot.initrd.luks.devices."luks-b8079894-672b-4182-8731-149664db7b80".device = "/dev/disk/by-uuid/b8079894-672b-4182-8731-149664db7b80";

  swapDevices =
    [ 
      {
        device = "/dev/disk/by-uuid/62bf4054-d1d5-4df8-893c-2e1058886908";
      }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f0u4.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
